### ISSUE TITLE
is there a place where we can swap decks?

### ISSUE THREAD

**Issue by grokskookum** [tallguyjenks/flash.sh#10]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by tallguyjenks** [comment]
what do you mean swap?

**Comment by tallguyjenks** [comment]
if you are `alexwagner74` from reddit, for others who wont see the reddit post, here was my response:

> if you export your anki deck to plan text you can then add the colon seperators and the required points field to the "cards" but for easy import/export, anki doesnt seem to export directly to csv. could probably download anki decks and export to txt then convert the cards to the format flash.sh uses.
>
>there are bashisms in flash.sh i believe (not 100% about what exactly or the portabiity) but im using bash on linux, not sure if OSx would be compatible with it with their old /bin/bash, plus im unfamiliar with mac file system, do they even have .local/share?

**Comment by grokskookum** [comment]
i see that ankiweb flash decks are just .zip files with an sqlite3 database inside, so you can basically do a query and output to csv from there. I am just wondering if you are going create a repo for decks that people can upload if they have taken the time to export or create them and they want to share.

**Comment by tallguyjenks** [comment]
that sounds like a terrific idea! i'll make it tonight in an hour or so

**Comment by tallguyjenks** [comment]
@grokskookum [the repo](https://github.com/tallguyjenks/Flash-Decks) is made and im fleshing out details, readme of flash.sh has also been updated to point to it, thanks again for the idea! :rocket:
