### ISSUE TITLE
Add newline support in question/answer fields

### ISSUE THREAD

**Issue by lambda2501** [tallguyjenks/flash.sh#41]
Hi ! 
It could be great to add the support of multiple lines on the question or answer fields.
For some of my cards, I need to insert a lot of informations.
I tried to add \n in csv fields, but it is not applied by the script.
I also tried to add the -e parameter to the echo commands on the script, but it changes nothing.
Any idea ?

Thanks in advance !

**Comment by mhdna** [comment]
@lambda2501 That's because you have to escape them with `\\n` not `\n` in your csv file.

**Comment by tallguyjenks** [comment]
as @mhdna stated, this serves that purpose
