### ISSUE TITLE
Updations in the readme file

### ISSUE THREAD

**Issue by shubhamshah14102** [tallguyjenks/flash.sh#42]
@tallguyjenks 
Hi ,
There are minute errors and scope of improvements in the first paragraph of the readme that are subtle but vivid.
Can you assign this issue to me?
Otherwise I would mention them here and you can correct it yourself

**Comment by tallguyjenks** [comment]
Assigned :)

**Comment by shubhamshah14102** [comment]
Hey .
How about adding the youtube link that inspired you to do this project??
Will make the project description in the readme look sophisticated and complete.
